### ISSUE TITLE
Ubi reader dont extract correctly the dump

### ISSUE THREAD

**Issue by markyy1991** [onekey-sec/ubi_reader#98]
-------------------------------------------------------------------------------------Error log-----------------------------------------------------------------------------

ubireader_display_info salida-1.BIN
UBI_File Warning: end_offset - start_offset length is not block aligned, could mean missing data.
Traceback (most recent call last):
  File "/usr/bin/ubireader_display_info", line 132, in <module>
    ubi_obj = ubi(ufile_obj)
              ^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/ubireader/ubi/__init__.py", line 146, in __init__
    super(ubi, self).__init__(ubi_file)
  File "/usr/lib/python3/dist-packages/ubireader/ubi/__init__.py", line 46, in __init__
    self._blocks = extract_blocks(self)
                   ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/ubireader/ubi/block/__init__.py", line 131, in extract_blocks
    blk.data_crc = (~crc32(buf[blk.ec_hdr.data_offset:blk.ec_hdr.data_offset+blk.vid_hdr.data_size]) & UBI_CRC32_INIT)
                                                                             ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'data_size'

----------------------------------------- operating system, python version, ubireader version-----------------------------------------------------------

kali linux last version
Python 3.12.6
Ubi reader version 0.8.9

--------------------------------------------File download--------------------------------------------------------------------------------------------------------------

https://fromsmash.com/Noecc1

**Comment by markyy1991** [comment]
I can  upload file if is necesary
